//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FlipNote
//  @ File Name : Aluno.java
//  @ Date : 24/5/2012
//  @ Author : Fernando Jorge Mota e Najuan Lóss Guth
//
//




/** */
public class Aluno {
	/** */
	private Object private int id;;
	
	/** */
	private Object private String nome;;
	
	/** */
	private Object private String email;;
	
	/** */
	private Object private String senha;;
	
	/** */
	public Trabalho trabalho;
	
	/** */
	public Materia materia;
	
	/** */
	public Prova prova;
	
	/** */
	public Anotacao anotação;
	
	/** */
	public Grupo grupo;
	
	/** */
	public void public Aluno() {
	
	}
	
	/** */
	public void public Aluno(Object int id, Object String nome, Object String email, Object String pwd) {
	
	}
	
	/** */
	public void public Aluno(Object String email, Object String pwd) {
	
	}
	
	/** */
	public void public int getID() {
	
	}
	
	/** */
	public void public String getNome() {
	
	}
	
	/** */
	public void public String getEmail() {
	
	}
	
	/** */
	public void public ArrayList<Materia> getMaterias() {
	
	}
	
	/** */
	public void public ArrayList<Prova> getProvas() {
	
	}
	
	/** */
	public void public ArrayList<Trabalho> getTrabalhos() {
	
	}
	
	/** */
	public void public ArrayList<Anotacao> getAnotacoes() {
	
	}
	
	/** */
	public void public ArrayList<Grupo> getGrupos() {
	
	}
	
	/** */
	public void public void setID(Object int id) {
	
	}
	
	/** */
	public void public void setNome(Object String nome) {
	
	}
	
	/** */
	public void public void setEmail(Object String email) {
	
	}
	
	/** */
	public void public void setSenha(Object String pwd) {
	
	}
	
	/** */
	public void public void insere() {
	
	}
	
	/** */
	public void public void atualiza() {
	
	}
	
	/** */
	public void public void apaga() {
	
	}
	
	/** */
	public void public void carrega() {
	
	}
}
