//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FlipNote
//  @ File Name : Anotacao.java
//  @ Date : 24/5/2012
//  @ Author : Fernando Jorge Mota e Najuan Lóss Guth
//
//




/** */
public class Anotacao {
	/** */
	private Object private int id;;
	
	/** */
	private Object private String titulo;;
	
	/** */
	private Object private String texto;;
	
	/** */
	private Object private Date notificacao;;
	
	/** */
	public Object private int aluno;;
	
	/** */
	public Object private int grupo;;
	
	/** */
	public void public Anotacao() {
	
	}
	
	/** */
	public void public Anotacao(Object int id, Object String titulo, Object String texto, Object Date notificacao, Object int aluno, Object int grupo) {
	
	}
	
	/** */
	public void public Anotacao(Object int id, Object String titulo, Object String texto, Object Date notificacao, Object int aluno) {
	
	}
	
	/** */
	public void public Anotacao(Object String titulo, Object String texto, Object Date notificacao, Object int aluno) {
	
	}
	
	/** */
	public void public Anotacao(Object String titulo, Object String texto, Object Date notificacao, Object int aluno, Object int grupo) {
	
	}
	
	/** */
	public void public int getID() {
	
	}
	
	/** */
	public void public String getTitulo() {
	
	}
	
	/** */
	public void public String getTexto() {
	
	}
	
	/** */
	public void public Date getNotificacao() {
	
	}
	
	/** */
	public void public Aluno getAluno() {
	
	}
	
	/** */
	public void public Grupo getGrupo() {
	
	}
	
	/** */
	public void public void setID(Object int novoID) {
	
	}
	
	/** */
	public void public void setTitulo(Object String novoTitulo) {
	
	}
	
	/** */
	public void public void setTexto(Object String novoTexto) {
	
	}
	
	/** */
	public void public voidd setNotificacao(Object Date novaNotificacao) {
	
	}
	
	/** */
	public void public void setAluno(Object int novoAluno) {
	
	}
	
	/** */
	public void public void setAluno(Object Aluno novoAluno) {
	
	}
	
	/** */
	public void public void setGrupo(Object int novoGrupo) {
	
	}
	
	/** */
	public void public void setGrupo(Object Grupo novoGrupo) {
	
	}
	
	/** */
	public void public void insere() {
	
	}
	
	/** */
	public void public void atualiza() {
	
	}
	
	/** */
	public void public void apaga() {
	
	}
	
	/** */
	public void public void carrega() {
	
	}
}
