//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FlipNote
//  @ File Name : Grupo.java
//  @ Date : 24/5/2012
//  @ Author : Fernando Jorge Mota e Najuan Lóss Guth
//
//




/** */
public class Grupo {
	/** */
	private Object private int id;;
	
	/** */
	private Object private String nome;;
	
	/** */
	private Object private String descricao;;
	
	/** */
	private Object private ArrayList<Aluno> alunos;;
	
	/** */
	public void public Grupo() {
	
	}
	
	/** */
	public void public Grupo(Object int id, Object String nome, Object String descricao, Object ArrayList<Aluno> alunos) {
	
	}
	
	/** */
	public void public Grupo(Object String nome, Object String descricao) {
	
	}
	
	/** */
	public void public int getID() {
	
	}
	
	/** */
	public void public String getNome() {
	
	}
	
	/** */
	public void public String getDescricao() {
	
	}
	
	/** */
	public void public ArrayList<Aluno> getAlunos() {
	
	}
	
	/** */
	public void public boolean hasAluno(Object Aluno aluno) {
	
	}
	
	/** */
	public void public void setID(Object int novoID) {
	
	}
	
	/** */
	public void public void setNome(Object String novoNome) {
	
	}
	
	/** */
	public void public void setDescricao(Object String novaDescricao) {
	
	}
	
	/** */
	public void public void addAluno(Object Aluno aluno) {
	
	}
	
	/** */
	public void public void removeAluno(Object Aluno aluno) {
	
	}
	
	/** */
	public void public void setAlunos(Object ArrayList<Aluno> novosAlunos) {
	
	}
	
	/** */
	public void public void removeTodosAlunos() {
	
	}
	
	/** */
	public void public void insere() {
	
	}
	
	/** */
	public void public void atualiza() {
	
	}
	
	/** */
	public void public void apaga() {
	
	}
	
	/** */
	public void public void carrega() {
	
	}
}
