//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FlipNote
//  @ File Name : Materia.java
//  @ Date : 24/5/2012
//  @ Author : Fernando Jorge Mota e Najuan Lóss Guth
//
//




/** */
public class Materia {
	/** */
	private Object private int id;;
	
	/** */
	private Object private String nome;;
	
	/** */
	private Object private String professor;;
	
	/** */
	private Object private int aluno;;
	
	/** */
	private Object private int grupo;;
	
	/** */
	public void public Materia() {
	
	}
	
	/** */
	public void public Materia(Object int id, Object String nome, Object String professor, Object int aluno, Object int grupo) {
	
	}
	
	/** */
	public void public Materia(Object String nome, Object String professor, Object int aluno, Object int grupo) {
	
	}
	
	/** */
	public void public Materia(Object int id, Object String nome, Object String professor, Object Aluno aluno, Object int grupo) {
	
	}
	
	/** */
	public void public Materia(Object String nome, Object String professor, Object Aluno aluno, Object int grupo) {
	
	}
	
	/** */
	public void public int getID() {
	
	}
	
	/** */
	public void public String getNome() {
	
	}
	
	/** */
	public void public String getProfessor() {
	
	}
	
	/** */
	public void public Aluno getAluno() {
	
	}
	
	/** */
	public void public Grupo getGrupo() {
	
	}
	
	/** */
	public void public void setID(Object int id) {
	
	}
	
	/** */
	public void public void setNome(Object String novoNome) {
	
	}
	
	/** */
	public void public void setProfessor(Object String novoProfessor) {
	
	}
	
	/** */
	public void public void setAluno(Object int novoAluno) {
	
	}
	
	/** */
	public void public void setAluno(Object Aluno novoAluno) {
	
	}
	
	/** */
	public void public void setGrupo(Object int novoGrupo) {
	
	}
	
	/** */
	public void public void setGrupo(Object Grupo novoGrupo) {
	
	}
	
	/** */
	public void public void insere() {
	
	}
	
	/** */
	public void public void atualiza() {
	
	}
	
	/** */
	public void public void apaga() {
	
	}
	
	/** */
	public void public void carrega() {
	
	}
}
