//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FlipNote
//  @ File Name : Trabalho.java
//  @ Date : 24/5/2012
//  @ Author : Fernando Jorge Mota e Najuan Lóss Guth
//
//




/** */
public class Trabalho {
	/** */
	private Object private int id;;
	
	/** */
	private Object private int materia;;
	
	/** */
	private Object private Date data;;
	
	/** */
	private Object private String descricao;;
	
	/** */
	private Object private Date notificacao;;
	
	/** */
	private Object private float nota;;
	
	/** */
	public void public Trabalho() {
	
	}
	
	/** */
	public void public Trabalho(Object int id, Object int materia, Object Date data, Object String descricao, Object Date notificacao, Object float nota) {
	
	}
	
	/** */
	public void public Trabalho(Object int materia, Object Date data, Object String descricao, Object Date notificacao) {
	
	}
	
	/** */
	public void public Trabalho(Object int id, Object Materia materia, Object Date data, Object String descricao, Object Date notificacao, Object float nota) {
	
	}
	
	/** */
	public void public Trabalho(Object Materia materia, Object Date data, Object String descricao, Object Date notificacao) {
	
	}
	
	/** */
	public void public int getID() {
	
	}
	
	/** */
	public void public Materia getMateria() {
	
	}
	
	/** */
	public void public Date getData() {
	
	}
	
	/** */
	public void public String getDescricao() {
	
	}
	
	/** */
	public void public Date getNotificacao() {
	
	}
	
	/** */
	public void public float getNota() {
	
	}
	
	/** */
	public void public void setID(Object int novoID) {
	
	}
	
	/** */
	public void public void setMateria(Object int novaMateria) {
	
	}
	
	/** */
	public void public void setMateria(Object Materia novaMateria) {
	
	}
	
	/** */
	public void public void setData(Object Date novaData) {
	
	}
	
	/** */
	public void public void setDescricao(Object String descricao) {
	
	}
	
	/** */
	public void public void setNotificacao(Object Date novaNotificacao) {
	
	}
	
	/** */
	public void public void setNota(Object float nota) {
	
	}
	
	/** */
	public void public void insere() {
	
	}
	
	/** */
	public void public void atualiza() {
	
	}
	
	/** */
	public void public void apaga() {
	
	}
	
	/** */
	public void public void carrega() {
	
	}
}
